### ISSUE TITLE
Port to 1.4.0.2

### ISSUE THREAD

**Issue by Pychnight** [Pychnight/TshockRpgToolKit#65]
Currently all plugins are needing to be ported over to the new terraria version

I have personally made progress with this.

All 1.4 changes should be pushed to the "indev" branch of this repo after everything is tested will be merged into the main branch.

Current problems

Housing Database issues

> [05/19/20 02:41:59] [Server API] Warning: Plugin "Housing" has had an unhandled exception thrown by one of its GameUpdate handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Housing.Extensions.IDatabaseExtensions.GetHouse(IDatabase database, Int32 x, Int32 y)
   at Housing.HousingPlugin.OnGameUpdate(EventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args) in d:\a\TShock\TShock\TerrariaServerAPI\TerrariaServerAPI\TerrariaApi.Server\HandlerCollection.cs:line  109

Other known bugs

Custom Npcs plugin

1. Custom monsters is not loading monsters properly.. (/cmob not showing, monsters can't be spawned using /csm)

2. Custom Invasions currently Broken 

Issues that really really should be fixed

#62 Config verification.
#53 Custom npcs loading fails / tries to load duplicate items

**Comment by Pychnight** [comment]
Resolved as of 4/3
